# Generated by Django 2.2.13 on 2020-06-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200624_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='bvccbvcbv',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='gfmhff',
        ),
    ]
