# Generated by Django 2.2.13 on 2020-06-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200624_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='dfgsdfg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='dfgsdfgs',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hytryuryu',
        ),
    ]
