# Generated by Django 2.2.13 on 2020-06-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_auto_20200624_0820"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="bvccbvcbv",),
        migrations.RemoveField(model_name="customtext", name="gfmhff",),
    ]
