# Generated by Django 2.2.13 on 2020-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200624_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='bvccbvcbv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='gfmhff',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
